name = "bloxlibs/betterscale"
version = "1.0.0"
description = "Responsive UI scaling for Roblox. Set it up once and forget about it."
authors = ["PcoiDev"]
repository = "https://github.com/blox-libs/BetterScale"
license = "BloxLibs"
includes = [
	"src/*",
	"README.md",
	"pesde.toml",
	"LICENSE"
]

[target]
environment = "roblox"
build_files = ["src"]
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
pesde = "^0.7.0"
